// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9WgmI_5LYe9JoCbUp5-q4NLubcavQcBo',
    appId: '1:644335047668:web:06b1f859c8c8b4569b1fa1',
    messagingSenderId: '644335047668',
    projectId: 'finance-tracker-f00ef',
    authDomain: 'finance-tracker-f00ef.firebaseapp.com',
    storageBucket: 'finance-tracker-f00ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZOMB1YhwZbLr36jb7N_VFZ5rLeaOWOnY',
    appId: '1:644335047668:android:47777078eb9127de9b1fa1',
    messagingSenderId: '644335047668',
    projectId: 'finance-tracker-f00ef',
    storageBucket: 'finance-tracker-f00ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4RNOboO-seE4nU8B20-sRqLTf_QlIoY',
    appId: '1:644335047668:ios:238e331cb0ff10869b1fa1',
    messagingSenderId: '644335047668',
    projectId: 'finance-tracker-f00ef',
    storageBucket: 'finance-tracker-f00ef.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg4RNOboO-seE4nU8B20-sRqLTf_QlIoY',
    appId: '1:644335047668:ios:238e331cb0ff10869b1fa1',
    messagingSenderId: '644335047668',
    projectId: 'finance-tracker-f00ef',
    storageBucket: 'finance-tracker-f00ef.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9WgmI_5LYe9JoCbUp5-q4NLubcavQcBo',
    appId: '1:644335047668:web:a5e8de8a84e4b6b59b1fa1',
    messagingSenderId: '644335047668',
    projectId: 'finance-tracker-f00ef',
    authDomain: 'finance-tracker-f00ef.firebaseapp.com',
    storageBucket: 'finance-tracker-f00ef.firebasestorage.app',
  );
}
